import type { Metadata } from "next";
import { Outfit } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

export const metadata: Metadata = {
  title: "smartlab",
  description: "Generated by create next app",
};

const bricolage = Outfit({
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" className={cn("h-full", "antialiased", "font-sans")}>
      <body
        className={`${bricolage.className} min-h-full flex flex-col bg-zinc-100`}
      >
        <div>{children}</div>
      </body>
    </html>
  );
}
