import type { Metadata } from "next";
import {
  Bricolage_Grotesque,
  Google_Sans,
  Inter,
  Urbanist,
  Encode_Sans,
  Syne,
} from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";

export const metadata: Metadata = {
  title: "smartlab",
  description: "Generated by create next app",
};

const bricolage = Inter({
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" className={cn("h-full", "antialiased", "font-sans")}>
      <body className={`${bricolage.className} min-h-full flex flex-col`}>
        <div>{children}</div>
      </body>
    </html>
  );
}
