import type { Metadata } from "next";
import { Bricolage_Grotesque, Google_Sans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Sidebar15 } from "./components/sidebar/Sidebar";

export const metadata: Metadata = {
  title: "smartlab",
  description: "Generated by create next app",
};

const bricolage = Google_Sans({
  subsets: ["latin"],
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br" className={cn("h-full", "antialiased", "font-sans")}>
      <body className={`${bricolage.className} min-h-full flex flex-col`}>
        <Sidebar15 />
        <div>{children}</div>
      </body>
    </html>
  );
}
